name: "tcp.Device.Modbus.Profile"
manufacturer: "Cool Automation"
model: "CoolMasterNet"
labels:
  - "ModBus TCP"

description: "modbus tcp"

deviceResources:
  - name: "SwitchA"
    description: "On/Off , 0-OFF 1-ON"
    attributes:
      { primaryTable: "COILS", startingAddress: "1" }
    properties:
      value:
        { type: "BOOL", readWrite: "RW", scale: "1", minimum: "0", maximum: "1", defaultValue: "0" }
      units:
        { type: "String", readWrite: "R", defaultValue: "On/Off" }

  - name: "SwitchB"
    description: "On/Off , 0-OFF 1-ON"
    attributes:
      { primaryTable: "COILS", startingAddress: "2" }
    properties:
      value:
        { type: "BOOL", readWrite: "RW", scale: "1", minimum: "0", maximum: "1", defaultValue: "0" }
      units:
        { type: "String", readWrite: "R", defaultValue: "On/Off" }

  - name: "Sensor1"
    description: "dragon description"
    attributes:
      { primaryTable: "HOLDING_REGISTERS", startingAddress: 1 }
    properties:
      value:
        { type: "INT16", readWrite: "RW", scale: "1", minimum: "0", maximum: "9", defaultValue: "0" }
      units:
        { type: "String", readWrite: "R", defaultValue: "defaultValue" }

  - name: "Sensor2"
    description: "dragon description"
    attributes:
      { primaryTable: "HOLDING_REGISTERS", startingAddress: 5 }
    properties:
      value:
        { type: "INT32", readWrite: "RW", scale: "1", minimum: "0", maximum: "9", defaultValue: "0" }
      units:
        { type: "String", readWrite: "R", defaultValue: "defaultValue" }

deviceCommands:
  - name: "SwitchA"
    get:
      - { index: "1", operation: "set", object: "SwitchA", parameter: "SwitchA" }
    set:
      - { index: "1", operation: "set", object: "SwitchA", parameter: "SwitchA" }

  - name: "SwitchB"
    get:
      - { index: "1", operation: "set", object: "SwitchB", parameter: "SwitchB" }
    set:
      - { index: "1", operation: "set", object: "SwitchB", parameter: "SwitchB" }

  - name: "Sensor1"
    get:
      - { index: "1", operation: "get", object: "Sensor1", parameter: "Sensor1" }
    set:
      - { index: "1", operation: "set", object: "Sensor1", parameter: "Sensor1" }

  - name: "Sensor2"
    get:
      - { index: "1", operation: "get", object: "Sensor2", parameter: "Sensor2" }
    set:
      - { index: "1", operation: "set", object: "Sensor2", parameter: "Sensor2" }

coreCommands:
  - name: "SwitchA"
    get:
      path: "/api/v1/device/{deviceId}/SwitchA"
      responses:
        - code: "200"
          description: "Get the Switch"
          expectedValues: [ "SwitchA" ]
        - code: "503"
          description: "service unavailable"
          expectedValues: [ ]
    put:
      path: "/api/v1/device/{deviceId}/SwitchA"
      parameterNames: [ "SwitchA" ]
      responses:
        - code: "204"
          description: "Set the SwitchA"
          expectedValues: [ ]
        - code: "503"
          description: "service unavailable"
          expectedValues: [ ]

  - name: "SwitchB"
    get:
      path: "/api/v1/device/{deviceId}/SwitchB"
      responses:
        - code: "200"
          description: "Get the Switch"
          expectedValues: [ "SwitchB" ]
        - code: "503"
          description: "service unavailable"
          expectedValues: [ ]
    put:
      path: "/api/v1/device/{deviceId}/SwitchB"
      parameterNames: [ "SwitchB" ]
      responses:
        - code: "204"
          description: "Set the SwitchB"
          expectedValues: [ ]
        - code: "503"
          description: "service unavailable"
          expectedValues: [ ]

  - name: "Sensor1"
    get:
      path: "/api/v1/device/{deviceId}/Sensor1"
      responses:
        - code: "200"
          description: "Get the HVAC values from the device"
          expectedValues: [ "Sensor1" ]
        - code: "503"
          description: "service unavailable"
          expectedValues: [ ]
    put:
      path: "/api/v1/device/{deviceId}/Sensor1"
      parameterNames: [ "Sensor1" ]
      responses:
        - code: "204"
          description: "Set the HVAC Values"
          expectedValues: [ ]
        - code: "503"
          description: "service unavailable"
          expectedValues: [ ]

  - name: "Sensor2"
    get:
      path: "/api/v1/device/{deviceId}/Sensor2"
      responses:
        - code: "200"
          description: "Get the HVAC values from the device"
          expectedValues: [ "Sensor2" ]
        - code: "503"
          description: "service unavailable"
          expectedValues: [ ]
    put:
      path: "/api/v1/device/{deviceId}/Sensor2"
      parameterNames: [ "Sensor2" ]
      responses:
        - code: "204"
          description: "Set the HVAC Values"
          expectedValues: [ ]
        - code: "503"
          description: "service unavailable"
          expectedValues: [ ]
