[Service]
Host = "edgex-device-modbus"
Port = 49991
ConnectRetries = 3
Labels = []
OpenMsg = "device modbus started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./device-Modbus.log"

[Writable]
LogLevel = "DEBUG"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res/example"

# Pre-define Devices
[[DeviceList]]
  Name = "Modbus_TCP_test_device"
  Profile = "Test.Device.Modbus.Profile"
  Description = "This device is a product for monitoring and controlling digital inputs and outputs over a LAN."
  labels = [ "Air conditioner","modbus TCP" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-tcp]
       Address = "192.168.1.190"
       Port = "1502"
       UnitID = "1"
  [[DeviceList.AutoEvents]]
    Frequency = "60s"
    OnChange = false
    Resource = "HVACValues"

#[[DeviceList]]
#  Name = "Modbus RTU test device"
#  Profile = "Test.Device.Modbus.Profile"
#  Description = "This device is a product for monitoring and controlling digital inputs and outputs over a LAN."
#  labels = [ "Air conditioner","modbus RTU" ]
#  [DeviceList.Protocols]
#    [DeviceList.Protocols.modbus-rtu]
#       Address = "/tmp/slave"
#       BaudRate = "19200"
#       DataBits = "8"
#       StopBits = "1"
#       Parity = "N"
#       UnitID = "1"
