[Service]
Host = "edgex-device-modbus"
Port = 49991
ConnectRetries = 3
Labels = []
OpenMsg = "device modbus started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./device-Modbus.log"

[Writable]
LogLevel = "DEBUG"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res/docker"

[[DeviceList]]
  Name = "室内温度传感器"
  Profile = "IndoorThermometer"
  Description = ""
  labels = [ "传感器","modbus RTU" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-rtu]
      Address = "/dev/ttyUSB0"
      BaudRate = "9600"
      DataBits = "8"
      StopBits = "1"
      Parity = "N"
      UnitID = "1"
    [[DeviceList.AutoEvents]]
      Frequency = "15s"
      OnChange = true
      Resource = "Sensor1"

[[DeviceList]]
  Name = "室外温度传感器"
  Profile = "OutdoorThermometer"
  Description = ""
  labels = [ "传感器","modbus RTU" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-rtu]
      Address = "/dev/ttyUSB0"
      BaudRate = "9600"
      DataBits = "8"
      StopBits = "1"
      Parity = "N"
      UnitID = "3"
    [[DeviceList.AutoEvents]]
      Frequency = "10s"
      OnChange = true
      Resource = "Sensor2"

[[DeviceList]]
  Name = "Modbus_RTU_device_ADAM4150_执行器"
  Profile = "ADAM4150.Device.Modbus.Profile"
  Description = "从串口485串口进行控制"
  labels = [ "执行器","modbus RTU" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-rtu]
      Address = "/dev/ttyUSB0"
      BaudRate = "9600"
      DataBits = "8"
      StopBits = "1"
      Parity = "N"
      UnitID = "2"
